services:
  postgresservice:
    image: postgresservice-image
    build:
      context: .
      dockerfile: postgres/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  managerservice:
    image: managerservice-image
    build:
      context: .
      dockerfile: manager/Dockerfile
    ports:
      - "5433:5433"
    networks:
      - microservices-net
    depends_on:
      #CHANGE 2: it prevents issuing a request while the server is starting to depend on the healthy status of postgres-db 
      postgresservice:
        condition: service_healthy

  webappservice:
    image: webappservice-image
    build:
      context: .
      dockerfile: webApp/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - microservices-net

networks:
  microservices-net: {}