services:
  postgresservice:
    image: postgresservice-image
    build:
      context: .
      dockerfile: postgres/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - microservices-net

  managerservice:
    image: managerservice-image
    build:
      context: .
      dockerfile: manager/Dockerfile
    ports:
      - "5433:5433"
    networks:
      - microservices-net

  # testservice:
  #   image: testservice-image
  #   build:
  #     context: .
  #     dockerfile: test/Dockerfile
  #   ports:
  #     - "5434:5434"
  #   networks:
  #     - microservices-net

networks:
  microservices-net: